/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 .\public\Models\Chair_model.gltf 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Chair_model(props) {
  const { nodes, materials } = useGLTF('./Models/Chair_model.gltf')
  return (
    <group {...props} dispose={null} scale={[0.1, 0.1, 0.1]}>
      <mesh geometry={nodes.Chair_lp.geometry} material={materials['Chair.001']} visible={false}/>
      <mesh geometry={nodes.chair001.geometry} material={materials.chair} scale={0.205} />
    </group>
  )
}

useGLTF.preload('./Models/Chair_model.gltf')
