/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 .\public\Models\v2\chairs_2.gltf 
*/

import React, { useEffect, useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { useCustomization } from "../constants/Customization_old";

export function Chairs_2(props) {
	const { nodes, materials } = useGLTF("./Models/v2/chairs_2.gltf");
	const { partToMeshMapping, arms, legs, back, cushion, seat } = useCustomization();

	return (
		<group {...props} dispose={null} scale={[0.1, 0.1, 0.1]}>
			<mesh
				geometry={nodes.classic_Arm.geometry}
				material={materials.chair}
				visible={partToMeshMapping['A'] === 1 && partToMeshMapping['A'] !== 0}
			/>
			<mesh
				geometry={nodes.classic_Back.geometry}
				material={materials.chair}
				visible={partToMeshMapping['B'] === 1 && partToMeshMapping['B'] !== 0}
			/>
			<mesh
				geometry={nodes.classic_Cushion.geometry}
				material={materials.chair}
				visible={partToMeshMapping['C'] === 1 && partToMeshMapping['C'] !== 0}
			/>
			<mesh
				geometry={nodes.classic_Seat.geometry}
				material={materials.chair}
				visible={partToMeshMapping['S'] === 1}
			/>
			<mesh
				geometry={nodes.classic_Legs.geometry}
				material={materials.chair}
				visible={partToMeshMapping['L'] === 1}
			/>
			<mesh
				geometry={nodes.mdr_Arm.geometry}
				material={materials.chair}
				visible={partToMeshMapping['B'] === 3  && partToMeshMapping['B'] !== 0}
			/>
			<mesh
				geometry={nodes.mdr_Back.geometry}
				material={materials.chair}
				visible={partToMeshMapping['B'] === 2 && partToMeshMapping['B'] !== 0}
			/>
			<mesh
				geometry={nodes.mdr_Cushion.geometry}
				material={materials.chair}
				visible={partToMeshMapping['C'] === 2 && partToMeshMapping['C'] !== 0}
			/>
			<mesh
				geometry={nodes.mdr_Legs.geometry}
				material={materials.chair}
				visible={partToMeshMapping['L'] === 2}
			/>
			<mesh
				geometry={nodes.mdr_Seat.geometry}
				material={materials.chair}
				visible={partToMeshMapping['S'] === 2}
			/>
		</group>
	);
}

useGLTF.preload("./Models/v2/chairs_2.gltf");
