/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 .\public\models2\part-2.gltf 
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { useCustomization } from "../../constants/Customization";

export function Part2(props) {
	const { nodes, materials } = useGLTF("./models2/part-2.gltf");
	const { codeOBJ } = useCustomization();

	return (
		<group {...props} dispose={null}>
			<group
				position={[16.666, 1.938, -15.443]}
				rotation={[-Math.PI / 2, 0, 0]}
				scale={0.021}
			>
				<mesh
					geometry={nodes.Material2282.geometry}
					material={materials.material}
				/>
				<mesh
					geometry={nodes.Material2282_1.geometry}
					material={materials.Color_F19}
				/>
				<mesh
					geometry={nodes.Material2282_2.geometry}
					material={materials.Translucent_Glass_Gray}
				/>
				<mesh
					geometry={nodes.Material2282_3.geometry}
					material={materials.Color_D02}
				/>
			</group>
			<mesh
				geometry={nodes["D-Self-main001"].geometry}
				material={materials.Pale_lancelot_oak_PBR}
				position={[15.205, 2.467, -18.085]}
				rotation={[-Math.PI / 2, 0, 0]}
				scale={0.021}
			/>
			<group
				position={[16.666, 1.938, -15.443]}
				rotation={[-Math.PI / 2, 0, 0]}
				scale={0.021}
			>
				<mesh
					geometry={nodes.Material2255.geometry}
					material={materials.material}
				/>
				<mesh
					geometry={nodes.Material2255_1.geometry}
					material={materials.Color_F19}
				/>
				<mesh
					geometry={nodes.Material2255_2.geometry}
					material={materials.Translucent_Glass_Gray}
				/>
				<mesh
					geometry={nodes.Material2255_3.geometry}
					material={materials.Color_D02}
				/>
			</group>
			<mesh
				geometry={nodes.Material2136.geometry}
				material={materials["vase-ode-to-baydo"]}
				position={[14.059, 2.441, -17.838]}
				rotation={[-Math.PI / 2, 0, 0]}
				scale={0.021}
			/>
			<mesh
				geometry={nodes.Material2124.geometry}
				material={materials.Color_M07}
				position={[19.596, 5.586, -14.97]}
				rotation={[-Math.PI / 2, 0, 0]}
			/>
			<mesh
				geometry={nodes.Material2025.geometry}
				material={materials.Translucent_Glass_Gray}
				position={[18.784, 5.807, -20.116]}
				rotation={[-Math.PI / 2, 0, 0]}
			/>
			<group
				position={[16.82, 4.004, -15.47]}
				rotation={[-Math.PI / 2, 0, 0]}
				scale={0.021}
			>
				<mesh
					geometry={nodes.Material2432.geometry}
					material={materials.Translucent_Glass_Gray}
				/>
				<mesh
					geometry={nodes.Material2432_1.geometry}
					material={materials.material_12}
				/>
				<mesh
					geometry={nodes.Material2432_2.geometry}
					material={materials.Color_M07}
				/>
				<mesh
					geometry={nodes.Material2432_3.geometry}
					material={materials.E27_3D_Emissive_White1}
				/>
			</group>
			<group
				position={[19.023, 2.037, -14.877]}
				rotation={[-Math.PI / 2, 0, 0]}
				scale={0.021}
			>
				<mesh
					geometry={nodes.Material2262.geometry}
					material={materials.Pale_lancelot_oak_PBR}
				/>
				<mesh
					geometry={nodes.Material2262_1.geometry}
					material={materials.Color_008}
				/>
				<mesh
					geometry={nodes.Material2262_2.geometry}
					material={
						materials["26_old_dirty_copper_metal_texture-seamless"]
					}
				/>
				<mesh
					geometry={nodes.Material2262_3.geometry}
					material={materials.Translucent_Glass_Gray}
				/>
				<mesh
					geometry={nodes.Material2262_4.geometry}
					material={materials.material}
				/>
				<mesh
					geometry={nodes.Material2262_5.geometry}
					material={materials["24_pool_water_texture_seamless"]}
				/>
			</group>
			<group
				position={[18.483, 1.625, -15.337]}
				rotation={[-Math.PI / 2, 0, 0]}
				scale={0.021}
				visible={codeOBJ["A"] === 0}
			>
				<mesh
					geometry={nodes.Material2214.geometry}
					material={materials["green-leather_texture-seamless"]}
				/>
				<mesh
					geometry={nodes.Material2214_1.geometry}
					material={materials.material_12}
				/>
				<mesh
					geometry={nodes.Material2214_2.geometry}
					material={materials.White_Painted_Stone_Tall_Green}
				/>
				<mesh
					geometry={nodes.Material2214_3.geometry}
					material={materials.PDM_Leather_BandB_AC_Lounge_2}
				/>
			</group>
			<group
				// sofa-B
				position={[15.33, 1.472, -15.921]}
				scale={[0.407, 0.407, 0.465]}
				visible={codeOBJ["A"] === 1}
			>
				<mesh
					geometry={nodes.Mesh001.geometry}
					material={materials.Sofa_Gray}
				/>
				<mesh
					geometry={nodes.Mesh001_1.geometry}
					material={materials.Sofa_Dark}
				/>
				<mesh
					geometry={nodes.Mesh001_2.geometry}
					material={materials.Material}
				/>
			</group>
			<mesh
				geometry={nodes["D-centerTable-B"].geometry}
				material={materials["Material.005"]}
				position={[16.753, 1.37, -15.377]}
				scale={0.407}
				visible={codeOBJ["B"] === 1}
			/>
			<group
				position={[16.926, 1.457, -15.313]}
				rotation={[-Math.PI / 2, 0, 0]}
				scale={0.021}
				visible={codeOBJ["B"] === 0}
			>
				<mesh
					geometry={nodes.Material2248.geometry}
					material={materials.material_12}
				/>
				<mesh
					geometry={nodes.Material2248_1.geometry}
					material={materials.Pale_lancelot_oak_PBR}
				/>
			</group>
			<mesh
				geometry={nodes["D-Rug-B"].geometry}
				material={materials.Sofa_Dark}
				position={[16.452, 1.37, -15.752]}
				scale={0.407}
			/>
			<group
				position={[16.586, 1.344, -15.547]}
				rotation={[-Math.PI / 2, 0, 0]}
				scale={0.021}
			>
				<mesh
					geometry={nodes.Material2273.geometry}
					material={
						materials[
							"Camel___Ivory_Rug__Labyrinth__-_Jonathan_Adler"
						]
					}
				/>
				<mesh
					geometry={nodes.Material2273_1.geometry}
					material={materials.Dense_Rattan}
				/>
			</group>
			<mesh
				geometry={nodes["D-Self-B"].geometry}
				material={materials.material_18}
				position={[15.186, 1.915, -18.076]}
				rotation={[-Math.PI / 2, 0, 0]}
				scale={0.021}
				visible={codeOBJ["C"] === 1}
			/>
			<group
				position={[15.205, 2.436, -18.052]}
				rotation={[-Math.PI / 2, 0, 0]}
				scale={0.021}
				visible={codeOBJ["C"] === 0}
			>
				<mesh
					geometry={nodes.Material2218.geometry}
					material={materials.material_12}
				/>
				<mesh
					geometry={nodes.Material2218_1.geometry}
					material={materials.Pale_lancelot_oak_PBR}
				/>
			</group>
			<group
				position={[16.947, 1.834, -21.103]}
				rotation={[-Math.PI / 2, 0, 0]}
				scale={0.021}
			>
				<mesh
					geometry={nodes.Material2267.geometry}
					material={materials.Dense_Rattan}
				/>
				<mesh
					geometry={nodes.Material2267_1.geometry}
					material={
						materials[
							"Camel___Ivory_Rug__Labyrinth__-_Jonathan_Adler"
						]
					}
				/>
			</group>
			<group
				position={[17.087, 2.128, -21.48]}
				rotation={[-Math.PI / 2, 0, 0]}
				scale={0.021}
			>
				<mesh
					geometry={nodes.Material2279.geometry}
					material={materials.material_12}
				/>
				<mesh
					geometry={nodes.Material2279_1.geometry}
					material={
						codeOBJ["dnTableTexture"] === 1
							? materials.sehpa_mermer__marble
							: materials.material_6
					}
				/>
				<mesh
					geometry={nodes.Material2279_2.geometry}
					material={
						materials["31_brushed_copper_metal_texture-seamless_6"]
					}
				/>
				<mesh
					geometry={nodes.Material2279_3.geometry}
					material={materials.Polished_Concrete_Old}
				/>
			</group>
			<group
				position={[15.763, 3.295, -21.151]}
				rotation={[-Math.PI / 2, 0, 0]}
				scale={0.021}
				visible={codeOBJ["dnClock"] === 1}
			>
				<mesh
					geometry={nodes.Material2114.geometry}
					material={materials.brushed_aluminium}
				/>
				<mesh
					geometry={nodes.Material2114_1.geometry}
					material={materials.WALL_CLOCK}
				/>
				<mesh
					geometry={nodes.Material2114_2.geometry}
					material={materials.material_12}
				/>
				<mesh
					geometry={nodes.Material2114_3.geometry}
					material={materials["23_brushed_dark_steel_metal"]}
				/>
			</group>
			<group
				visible={codeOBJ["dnLamp"] === 4}
				position={[16.928, 4.182, -21.346]}
			>
				<mesh
					geometry={nodes.Material2521.geometry}
					material={materials.Translucent_Glass_Gray}
				/>
				<mesh
					geometry={nodes.Material2521_1.geometry}
					material={
						materials["26_old_dirty_copper_metal_texture-seamless"]
					}
				/>
				<mesh
					geometry={nodes.Material2521_2.geometry}
					material={materials.Color_M07}
				/>
			</group>
			<group
				position={[16.928, 4.143, -21.349]}
				visible={codeOBJ["dnLamp"] === 2}
			>
				<mesh
					geometry={nodes.Circle003.geometry}
					material={materials["Car plastic dark"]}
				/>
				<mesh
					geometry={nodes.Circle003_1.geometry}
					material={materials["filament_Light "]}
				/>
				<mesh
					geometry={nodes.Circle003_2.geometry}
					material={materials["metal.002"]}
				/>
				<mesh
					geometry={nodes.Circle003_3.geometry}
					material={materials.Steel}
				/>
				<mesh
					geometry={nodes.Circle003_4.geometry}
					material={materials.Glass}
				/>
			</group>
			<group
				position={[16.93, 4.168, -22.02]}
				visible={codeOBJ["dnLamp"] === 1}
			>
				<mesh
					geometry={nodes.Mesh157.geometry}
					material={materials["tepa.001"]}
				/>
				<mesh
					geometry={nodes.Mesh157_1.geometry}
					material={materials["xlor up.001"]}
				/>
				<mesh
					geometry={nodes.Mesh157_2.geometry}
					material={materials["lampa.001"]}
				/>
				<mesh
					geometry={nodes.Mesh157_3.geometry}
					material={materials["xrom.001"]}
				/>
				<mesh
					geometry={nodes.Mesh157_4.geometry}
					material={materials["Material #29.001"]}
				/>
				<mesh
					geometry={nodes.Mesh157_5.geometry}
					material={materials["Material #30.001"]}
				/>
				<mesh
					geometry={nodes.Mesh157_6.geometry}
					material={materials["simi.001"]}
				/>
				<mesh
					geometry={nodes.Mesh157_7.geometry}
					material={materials["01 wood.001"]}
				/>
				<mesh
					geometry={nodes.Mesh157_8.geometry}
					material={materials["01.001"]}
				/>
				<mesh
					geometry={nodes.Mesh157_9.geometry}
					material={materials["02 wood.001"]}
				/>
				<mesh
					geometry={nodes.Mesh157_10.geometry}
					material={materials["02.001"]}
				/>
				<mesh
					geometry={nodes.Mesh157_11.geometry}
					material={materials["03 wood.001"]}
				/>
				<mesh
					geometry={nodes.Mesh157_12.geometry}
					material={materials["03.001"]}
				/>
			</group>
			<group
				position={[16.913, 4.184, -22.016]}
				visible={codeOBJ["dnLamp"] === 3}
			>
				<mesh
					geometry={nodes.Mesh170.geometry}
					material={materials["03"]}
				/>
				<mesh
					geometry={nodes.Mesh170_1.geometry}
					material={materials.simi}
				/>
				<mesh
					geometry={nodes.Mesh170_2.geometry}
					material={materials["lampa.001"]}
				/>
				<mesh
					geometry={nodes.Mesh170_3.geometry}
					material={materials.tepa}
				/>
				<mesh
					geometry={nodes.Mesh170_4.geometry}
					material={materials["03 wood"]}
				/>
			</group>
			<group
				position={[16.921, 4.184, -22.014]}
				visible={codeOBJ["dnLamp"] === 5}
			>
				<mesh
					geometry={nodes.Mesh171.geometry}
					material={materials["03"]}
				/>
				<mesh
					geometry={nodes.Mesh171_1.geometry}
					material={materials.simi}
				/>
				<mesh
					geometry={nodes.Mesh171_2.geometry}
					material={materials.lampa}
				/>
				<mesh
					geometry={nodes.Mesh171_3.geometry}
					material={materials.tepa}
				/>
			</group>
			<group
				position={[16.962, 2.212, -20.138]}
				rotation={[-Math.PI / 2, 0, 1.865]}
				scale={0.021}
			>
				<mesh
					geometry={nodes.Material2298.geometry}
					material={materials["23_brushed_dark_steel_metal"]}
				/>
				<mesh
					geometry={nodes.Material2298_1.geometry}
					material={
						materials["31_brushed_copper_metal_texture-seamless"]
					}
				/>
				<mesh
					geometry={nodes.Material2298_2.geometry}
					material={materials.material_12}
				/>
				<mesh
					geometry={nodes.Material2298_3.geometry}
					material={materials.PDM_Leather_BandB_AC_Lounge_2}
				/>
			</group>
			<mesh
				geometry={nodes.Material2028.geometry}
				material={materials["Smart-TV-Menu"]}
				rotation={[-Math.PI / 2, 0, 0]}
				scale={0.021}
			/>
			<mesh
				geometry={nodes.Material2029.geometry}
				material={materials.Color_008}
				rotation={[-Math.PI / 2, 0, 0]}
				scale={0.021}
			/>
			<mesh
				geometry={nodes.Material2033.geometry}
				material={materials.material}
				rotation={[-Math.PI / 2, 0, 0]}
				scale={0.021}
			/>
			<mesh
				geometry={nodes.Material2043.geometry}
				material={materials.Vegetation_Bark_Maple2}
				rotation={[-Math.PI / 2, 0, 0]}
				scale={0.021}
			/>
			<mesh
				geometry={nodes.Material2044.geometry}
				material={materials.material_6}
				rotation={[-Math.PI / 2, 0, 0]}
				scale={0.021}
			/>
		</group>
	);
}

useGLTF.preload("./models2/part-2.gltf");
